import { Question } from "../all_questions";

export const questions: Question[] = [
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Words in Context",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_1",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text with the most logical and precise word or phrase?\nThe reception of Many Ly's book *Roots and wings* has been very good. Many reviewers, booksellers, and librarians have ______ the book, and it won the Asian/Pacific American Award for Literature.",
    "choices": [
      {
        "id": "A",
        "text": "attacked"
      },
      {
        "id": "B",
        "text": "recommended"
      },
      {
        "id": "C",
        "text": "overlooked"
      },
      {
        "id": "D",
        "text": "misunderstood"
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Words in Context",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Words in Context",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_2",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "As used in the text, what does the word \"conceivable\" most nearly mean?\nThe following text is adapted from Mary Seacole's 1857 autobiography *Wonderful Adventures of Mr. Seacole in Many Lands*. That journey across the Isthmus [of Panama], insignificant in distance as it was, was by no means an easy one. It seemed as if nature had determined to throw every <u>conceivable</u> obstacle in the way of those who should seek to join the two great oceans of the world.",
    "choices": [
      {
        "id": "A",
        "text": "Visible"
      },
      {
        "id": "B",
        "text": "Steady"
      },
      {
        "id": "C",
        "text": "Easy"
      },
      {
        "id": "D",
        "text": "Possible"
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Words in Context",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Words in Context",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_3",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text with the most logical and precise word or phrase?\nKelp forests grow underwater along the eastern Pacific Coast. These underwater forests are important to fish and other marine animals. Ocean currents can be powerful and rough, making it difficult for animals to find safe places to hide from predators. The underwater forests slow down the currents. This creates a more ______ environment with calmer waters where animals can take shelter.",
    "choices": [
      {
        "id": "A",
        "text": "surprising"
      },
      {
        "id": "B",
        "text": "dangerous"
      },
      {
        "id": "C",
        "text": "tranquil"
      },
      {
        "id": "D",
        "text": "imaginative"
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Words in Context",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Words in Context",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_4",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text with the most logical and precise word or phrase?\nThe recently observed gamma ray burst GRB 230307A lasted for 200 seconds, ______ for a burst generated by the merger of neutron stars. Bursts caused by neutron mergers typically last fewer than 2 seconds.",
    "choices": [
      {
        "id": "A",
        "text": "an oddity"
      },
      {
        "id": "B",
        "text": "a coincidence"
      },
      {
        "id": "C",
        "text": "a reprieve"
      },
      {
        "id": "D",
        "text": "an incident"
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Words in Context",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Text Structure and Purpose",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_5",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice best describes the main purpose of the text?\nPteropods are small swimming snails with thin, delicate calcium carbonate shells. These animals are thought to be especially vulnerable to ocean acidification due to calcium carbonate's susceptibility to dissolution at lower pH values. Victoria L. Peck and colleagues recently found that the periostracum (a protective coating on pteropods' outer shells) prevents this dissolution when intact. Moreover, the team was surprised to discover that even when the periostracum is breached, pteropods can still mitigate damage by rebuilding the inner shell wall.",
    "choices": [
      {
        "id": "A",
        "text": "To call for additional research on biological mechanisms that improve pteropod survival rates"
      },
      {
        "id": "B",
        "text": "To present findings that suggest that a concern about the effects of ocean acidification on pteropod shells may be unwarranted"
      },
      {
        "id": "C",
        "text": "To address some of the ways ocean acidification has altered pteropod behavior over time"
      },
      {
        "id": "D",
        "text": "To discuss a conclusion drawn in a study of calcium carbonate's role in protecting the periostracum of pteropods"
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Text Structure and Purpose",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Craft and Structure",
    "skill": "Text Structure and Purpose",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_6",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice best states the main purpose of the text?\nSan Francisco has high pedestrian traffic, but simply replicating a feature of San Francisco associated with walkability—e.g., its high density of storefronts—may be insufficient to induce increased walking in other cities. As urbanist Mariela Alfonzo argues, our understanding of individuals' decision-making about whether to walk is insufficiently robust: some studies emphasize the role of demographic characteristics, others the role of public transit availability, and so on, but walking decisions are made in complex contexts in which multiple conditions and needs inform individuals' choices.",
    "choices": [
      {
        "id": "A",
        "text": "To discuss the difficulty of identifying a reliable way to increase walking in any given city"
      },
      {
        "id": "B",
        "text": "To explain why it is challenging to compare the amount of pedestrian traffic in different cities"
      },
      {
        "id": "C",
        "text": "To describe the effect of a high density of storefronts on any given city's walkability"
      },
      {
        "id": "D",
        "text": "To present a claim about how individuals' decision-making about walking can be improved"
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Craft and Structure",
      "skill": "Text Structure and Purpose",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Central Ideas and Details",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_7",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "According to the text, which choice best describes a conclusion He and colleagues drew from their study?\nGuojun He and colleagues studied a food-delivery phone app that is popular in China. The researchers found that having \"no cutlery\" automatically selected influences whether customers request disposable plastic utensils with their food orders. Based on their results, the researchers concluded that this and other small changes to the app could reduce plastic waste in China by as much as 3.26 million metric tons per year.",
    "choices": [
      {
        "id": "A",
        "text": "Production of plastic waste in China is likely to increase in the near future."
      },
      {
        "id": "B",
        "text": "Food-delivery apps that prevent customers from requesting cutlery are becoming more popular."
      },
      {
        "id": "C",
        "text": "Customers who understand how food-delivery apps work make more environmentally friendly choices."
      },
      {
        "id": "D",
        "text": "Small changes to how a food-delivery app works can greatly lower plastic waste."
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Central Ideas and Details",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Inferences",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_8",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "In the text, which point does Prospero most directly make about Miranda and her memories?\nThe following text is from William Shakespeare's play *The Tempest*, first performed in 1611. Miranda has lived on an island with her father, Prospero, since she was three years old. Prospero has stated that Miranda likely does not remember anything other than her life on the island. MIRANDA: 'Tis far off,\nAnd rather like a dream than an assurance\nThat my remembrance warrants. Had I not\nFour or five women once that tended me?\nPROSPERO: Thou hadst, and more, Miranda. But how is it\nThat this lives in thy mind? What seest thou else\nIn the dark backward and abysm of time?\nIf thou remember'st ought ere thou camest here,\nHow thou camest here thou mayst.",
    "choices": [
      {
        "id": "A",
        "text": "Miranda's impression of a scene is vague because she is remembering a scenario she had daydreamed about as a child rather than a scenario that had occurred in reality."
      },
      {
        "id": "B",
        "text": "Miranda's reminiscences about her early childhood have a melancholy quality that betrays her discontented view of her current circumstances."
      },
      {
        "id": "C",
        "text": "Miranda's ability to summon details of an experience she had before arriving on the island suggests that she may also be able to summon details of her arrival on the island."
      },
      {
        "id": "D",
        "text": "Miranda's doubts about the accuracy of one recollection of a place other than the island are clouding her judgment and seem to be making her reluctant to explore her recollection of traveling to the island."
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Inferences",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Command of Evidence",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_9",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most effectively uses data from the table to complete the statement?\nThe Chickasaw Nation and the nearly forty other tribes in Oklahoma operate numerous businesses and collectively generate billions of dollars in revenue. Mining, including oil and natural gas production, is a key industry in the state as well. While researching other key industries in Oklahoma for an economics class, a student finds that the average amount contributed to the state's economy in 2017 by each individual employed in wholesale trade was ______.",
    "choices": [
      {
        "id": "A",
        "text": "$141,510."
      },
      {
        "id": "B",
        "text": "$56,163."
      },
      {
        "id": "C",
        "text": "$183,790."
      },
      {
        "id": "D",
        "text": "$96,964."
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Command of Evidence",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Command of Evidence",
    "difficulty": "Easy",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_10",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most effectively uses data from the table to complete the statement?\nA marine biologist is researching four stony coral species in Caribbean and Indo-Pacific waters, focusing on sightings of these species in the shallow zone (less than 30 meters below the surface) and the mesophotic zone (30 to 150 meters below the surface). Consulting the table, she notes that the smallest maximum depth is located in ______.",
    "choices": [
      {
        "id": "A",
        "text": "Indo-Pacific waters in the shallow zone"
      },
      {
        "id": "B",
        "text": "Caribbean waters in the shallow zone"
      },
      {
        "id": "C",
        "text": "Indo-Pacific waters in the mesophotic zone"
      },
      {
        "id": "D",
        "text": "Caribbean waters in the mesophotic zone"
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Command of Evidence",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Command of Evidence",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_11",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice best describes data from the graph that support the student's claim?\nIn a college course on urban affairs, a student asserts that increased traffic congestion in the United States in the 1990s was present both in very large cities such as Philadelphia, Pennsylvania, and smaller areas such as Albany-Schenectady-Troy, New York, and Beaumont, Texas; though those smaller areas may have been less affected by traffic congestion than very large cities, this congestion also worsened in them over time.",
    "choices": [
      {
        "id": "A",
        "text": "Even though the amount of traffic delay per commuter per year was greater in the Albany-Schenectady-Troy, New York, area than in the Philadelphia, Pennsylvania, area throughout the period from 1990 to 2000, the amounts were nearly identical in 1996."
      },
      {
        "id": "B",
        "text": "In 1992, the amount of traffic delay in the Philadelphia, Pennsylvania, area was less than 30 hours per commuter per year."
      },
      {
        "id": "C",
        "text": "In at least one of the three urban areas shown, the amount of traffic delay was less than 20 hours per commuter per year at one point between 1990 and 2000"
      },
      {
        "id": "D",
        "text": "While the annual number of hours of traffic delay per commuter was always lower in the Albany-Schenectady-Troy, New York, area than in the Philadelphia, Pennsylvania, area for each year between 1990 and 2000, the amount of traffic delay rose in both areas during this period."
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Command of Evidence",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Command of Evidence",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_12",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which finding, if true, would most directly support the researchers' claim?\nPast research suggests that pollination by honeybees is responsible for up to 10 percent of total Chinese cabbage crop production. Now researchers are trying to determine how dependent cucumber crop production is on honeybees. The first phase of their study involved shielding some cucumber plants to prevent insects from pollinating them, resulting in those plants having 40 to 90 percent lower crop production than plants that were pollinated normally. However, the researchers claim that the first-phase experiment alone didn't tell them how much of that difference in crop production is due specifically to excluding honeybees.",
    "choices": [
      {
        "id": "A",
        "text": "The shielding used in the first phase of the study did not affect the amount of sunlight the cucumber plants received."
      },
      {
        "id": "B",
        "text": "Other insects like solitary bees also pollinate Chinese cabbage plants, and some studies have allowed them to pollinate normally while excluding honeybees."
      },
      {
        "id": "C",
        "text": "Other insects like squash bees also pollinate cucumber plants, and the shielding in the first phase of the study blocked them as well."
      },
      {
        "id": "D",
        "text": "Honeybees are more commonly used to pollinate cucumber plants than Chinese cabbage plants."
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Command of Evidence",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Inferences",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_13",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most logically completes the text?\nThe glossy ibis and the small dark heron are long-legged birds that live in wetlands, like the Everglades in Florida. Laura D'Acunto and colleagues wanted to know how these birds choose an area in which to live. They looked at features of the birds' habitats, such as the geographic location of the area and how deep the water is during the birds' breeding season. They found that glossy ibises prefer areas with deep water during breeding season, but that was not true for small dark herons. The researchers concluded that water management strategies that increase the depth of water in potential wetland bird habitats during breeding season are therefore more likely to ______",
    "choices": [
      {
        "id": "A",
        "text": "attract glossy ibises to the area than they are to attract small dark herons to the area."
      },
      {
        "id": "B",
        "text": "attract birds that don't typically live in wetlands to the area than they are to attract glossy ibises or small dark herons to the area."
      },
      {
        "id": "C",
        "text": "extend the average lifespan of glossy ibises already in the area than they are to attract a greater number of those birds to the area."
      },
      {
        "id": "D",
        "text": "decrease the area's appeal to both glossy ibises and small dark herons than they are to increase the appeal to either."
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Inferences",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Information and Ideas",
    "skill": "Inferences",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_14",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most logically completes the text?\nScientists recently created a model to predict how increasing human activity will affect future mammal population sizes in Us national forests. Unfortunately, when the model is applied to large forests, its predictions for large-mammal populations are too high, and when applied to small forests, its predictions for small-mammal populations are too high. Beaverhead-Deerlodge National Forest in Montana is a large forest, covering more than 3 million acres. If used to evaluate the effect of increasing human activity on this forest in ten years, the model would likely therefore ______",
    "choices": [
      {
        "id": "A",
        "text": "exaggerate the effect of increasing human activity on small mammals."
      },
      {
        "id": "B",
        "text": "overestimate the actual population sizes of large mammals."
      },
      {
        "id": "C",
        "text": "ignore the predator-prey relationships between large and small mammals."
      },
      {
        "id": "D",
        "text": "reflect factors affecting large mammals other than increasing human activity."
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Information and Ideas",
      "skill": "Inferences",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Form, Structure, and Sense",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_15",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nIn 1989, Missouri ______ official fossil: the *Eperisocrinus*, which is a Carboniferous period marine animal.",
    "choices": [
      {
        "id": "A",
        "text": "lawmaker's designated the states"
      },
      {
        "id": "B",
        "text": "lawmakers designated the state's"
      },
      {
        "id": "C",
        "text": "lawmaker's designated the state's"
      },
      {
        "id": "D",
        "text": "lawmakers designated the states"
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Form, Structure, and Sense",
      "confidence": "medium"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Form, Structure, and Sense",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_16",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nOften anthologized alongside the ______ associated with the Black Arts movement—such as Henry Dumas and Ntozake Shange—Aki Madhubuti's poem \"Quality: Gwendolyn Brooks at 73\" stands out for its memorable first lines: \"breath, / life after seven decades plus three years / is a lot of breathing.”",
    "choices": [
      {
        "id": "A",
        "text": "works of other writer's"
      },
      {
        "id": "B",
        "text": "work's of other writer's"
      },
      {
        "id": "C",
        "text": "works of other writers"
      },
      {
        "id": "D",
        "text": "work's of other writers"
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Form, Structure, and Sense",
      "confidence": "medium"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Boundaries",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_17",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nThe part of a compound that determines the compound's color is ______ the chromophore. One example of a chromophore is hemoglobin, which gives human blood its red color.",
    "choices": [
      {
        "id": "A",
        "text": "called—"
      },
      {
        "id": "B",
        "text": "called;"
      },
      {
        "id": "C",
        "text": "called,"
      },
      {
        "id": "D",
        "text": "called"
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Boundaries",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Boundaries",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_18",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nReleased in 1993, the Intel Pentium microchip contained a single CPU, or core, to execute commands. Since then, the average processing power of microchips has increased so drastically—cores now number in the dozens, hundreds, or even ______ the once-revolutionary dual-core technology that replaced the single-core chip can be found in everyday items like toasters and toothbrushes.",
    "choices": [
      {
        "id": "A",
        "text": "thousands—that"
      },
      {
        "id": "B",
        "text": "thousands that—"
      },
      {
        "id": "C",
        "text": "thousands. That"
      },
      {
        "id": "D",
        "text": "thousands, that"
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Boundaries",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Boundaries",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_19",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nAfter finding information about Ronald V. Dellums, who represented California in the United States House of Representatives, the student discovered biographical sketches of two other Black Americans who served in ______ Ralph Harold Metcalfe of Illinois and George Henry White of North Carolina.",
    "choices": [
      {
        "id": "A",
        "text": "Congress."
      },
      {
        "id": "B",
        "text": "Congress:"
      },
      {
        "id": "C",
        "text": "Congress;"
      },
      {
        "id": "D",
        "text": "Congress"
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Boundaries",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Standard English Conventions",
    "skill": "Form, Structure, and Sense",
    "difficulty": "Medium",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_20",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text so that it conforms to the conventions of Standard English?\nWhen a given industry—water and electricity are two well-known examples—carries high infrastructural start-up costs and other barriers that discourage competition, ______ of just one or two suppliers per municipality. Such industries are known as natural monopolies.",
    "choices": [
      {
        "id": "A",
        "text": "they often consist"
      },
      {
        "id": "B",
        "text": "this often consists"
      },
      {
        "id": "C",
        "text": "these often consist"
      },
      {
        "id": "D",
        "text": "it often consists"
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Standard English Conventions",
      "skill": "Form, Structure, and Sense",
      "confidence": "medium"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Transitions",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_21",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text with the most logical transition?\nCornelia Konrads is a German sculptor who creates art that seems to be part of its surroundings. Her sculpture entitled *knotty stilts* is built on the wall of a university building in the United States. ______ appearing as two support beams knotted together against the wall, it is cleverly placed into its environment, serving as an example of Konrads's approach.",
    "choices": [
      {
        "id": "A",
        "text": "There,"
      },
      {
        "id": "B",
        "text": "Later,"
      },
      {
        "id": "C",
        "text": "For instance,"
      },
      {
        "id": "D",
        "text": "However,"
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Transitions",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Transitions",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_22",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice completes the text with the most logical transition?\nThere are three basic steps you should follow when planning a scientific inquiry. First, thoroughly research the question you wish to answer. ______ come up with a prediction (also called a hypothesis) about the answer to your question. Third, develop an experiment that can test the accuracy of your hypothesis.",
    "choices": [
      {
        "id": "A",
        "text": "For example,"
      },
      {
        "id": "B",
        "text": "Second,"
      },
      {
        "id": "C",
        "text": "Therefore,"
      },
      {
        "id": "D",
        "text": "Instead,"
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Transitions",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Rhetorical Synthesis",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_23",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most effectively uses information from the given sentences to introduce Reginald Fessenden and what he is known for?\nWhile researching a topic, a student has taken the following notes:\n• Thomas Edison is regarded as one of the most important inventors in US history.\n• Having received little formal schooling, Edison relied on specialist employees at his various laboratories and offices to complete the technical work for many of his inventions.\n• Reginald Fessenden was an electronic communications specialist who worked at the Edison Machine Works manufacturing company.\n• He is best known for pioneering radio technology that led to the first transmission of speech by radio.\n• Frank J. Sprague was a naval officer who worked at the Menlo Park laboratory.\n• He is best known for being the father of electric traction.",
    "choices": [
      {
        "id": "A",
        "text": "Reginald Fessenden, an electronic communications specialist, worked at the Edison Machine Works manufacturing company."
      },
      {
        "id": "B",
        "text": "Reginald Fessenden, an electronic communications specialist and former employee of Thomas Edison, is known for pioneering radio technology that led to the first transmission of speech by radio."
      },
      {
        "id": "C",
        "text": "Having received little formal education, Thomas Edison depended on specialized employees, including Reginald Fessenden and Frank J. Sprague, for many of his inventions."
      },
      {
        "id": "D",
        "text": "Thomas Edison's historic success would not have been possible without naval officer Frank J. Sprague, who is known for being the father of electric traction."
      }
    ],
    "correctAnswer": "B",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Rhetorical Synthesis",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Rhetorical Synthesis",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_24",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "The student wants to emphasize the size of Atitalaquía. Which choice most effectively uses relevant information from the notes to accomplish this goal?\nWhile researching a topic, a student has taken the following notes:\n• Atitalaquía is a municipality in the state of Hidalgo, Mexico.\n• Municipalities are governmental regions responsible for providing many public services to their residents.\n• One service they provide is street lighting.\n• Atitalaquía covers an area of roughly 63 km 2.\n• Hidalgo is divided into 84 municipalities.",
    "choices": [
      {
        "id": "A",
        "text": "Providing street lighting is just one example of the public services that municipalities provide."
      },
      {
        "id": "B",
        "text": "Atitalaquía is one of 84 governmental regions, known as municipalities, across Hidalgo."
      },
      {
        "id": "C",
        "text": "Atitalaquía—a governmental region in the state of Hidalgo, Mexico—provides many public services to its residents."
      },
      {
        "id": "D",
        "text": "The municipality of Atitalaquía in Hidalgo, Mexico, covers an area of roughly 63 km 2."
      }
    ],
    "correctAnswer": "D",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Rhetorical Synthesis",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Rhetorical Synthesis",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_25",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "The student wants to provide a quotation from chapter 17. Which choice most effectively uses relevant information from the notes to accomplish this goal?\nWhile researching a topic, a student has taken the following notes:\n• *The Future of Nostalgia* is a scholarly book by literary theorist Svetlana Boym.\n• The book provides a multifaceted exploration of the concept of nostalgia.\n• Chapter 9 describes nostalgia in the city of St. Petersburg in Russia.\n• Chapter 17 discusses various skeptics' takes on the concept of nostalgia.\n• In chapter 17, Boym writes, \"The poethics of nostalgia combines estrangement and human solidarity, affect and reflection.\"",
    "choices": [
      {
        "id": "A",
        "text": "In a discussion of various skeptics' takes on the concept of nostalgia, Svetlana Boym writes, \"The poethics of nostalgia combines estrangement and human solidarity, affect and reflection.\""
      },
      {
        "id": "B",
        "text": "Svetlana Boym's *The Future of Nostalgia* provides a multifaceted exploration of nostalgia."
      },
      {
        "id": "C",
        "text": "Svetlana Boym describes nostalgia in the city of St. Petersburg in Russia in chapter 9 of her book."
      },
      {
        "id": "D",
        "text": "After describing nostalgia in the city of St. Petersburg in Russia, Svetlana Boym goes on to discuss various skeptics' takes on the concept of nostalgia."
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Rhetorical Synthesis",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Rhetorical Synthesis",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_26",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "Which choice most effectively uses information from the given sentences to emphasize how the two works are similar?\nWhile researching a topic, a student has taken the following notes:\n• Jean-Michel Basquiat was an American artist who produced more than two thousand drawings and paintings.\n• His work *Untitled (Two Heads on Gold)* was completed in 1982 and sold at auction in 2003.\n• *Untitled (Two Heads on Gold)* is composed of acrylic and oil stick on canvas and measures 10,000 square inches in area.\n• His work *Jazz* was completed in 1986 and sold at auction in 2020.\n• *Jazz* is composed of acrylic, oil, graphite, crayon, and paper collage on wood and measures 1,807 square inches in area.",
    "choices": [
      {
        "id": "A",
        "text": "Artist Jean-Michel Basquiat completed *Untitled (Two Heads on Gold)* in 1982, and *Jazz* followed in 1986."
      },
      {
        "id": "B",
        "text": "Between artist Jean-Michel Basquiat's works *Untitled (Two Heads on Gold)* and *Jazz*, the former is the larger of the two."
      },
      {
        "id": "C",
        "text": "Composed by artist Jean-Michel Basquiat in 1982 and 1986, respectively, both *Untitled (Two Heads on Gold)* and *Jazz* use acrylic paint as a medium."
      },
      {
        "id": "D",
        "text": "Artist Jean-Michel Basquiat's work *Untitled (Two Heads on Gold)* is composed of acrylic and oil stick, while *Jazz* is composed of acrylic, oil, graphite, crayon, and paper collage."
      }
    ],
    "correctAnswer": "C",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Rhetorical Synthesis",
      "confidence": "high"
    }
  },
  {
    "section": "Reading and Writing",
    "domain": "Expression of Ideas",
    "skill": "Rhetorical Synthesis",
    "difficulty": "Hard",
    "rationale": null,
    "id": "27f42b6d-5bcd-4609-9ebb-429b11fd782b_27",
    "testName": "August 2024 International Form D SAT English Module 1",
    "text": "The student wants to contrast two words that represent the same sound. Which choice most effectively uses relevant information from the notes to accomplish this goal?\nWhile researching a topic, a student has taken the following notes:\n• Onomatopoeias are words that imitate the sounds they represent.\n• Words that represent the same sound are often written and pronounced very differently from language to language.\n• This variation is due in part to differences in how the languages are structured.\n• \"Korrrr\" is a Batak onomatopoeia that represents the sound of snoring.\n• \"Hu lu\" is a Mandarin Chinese onomatopoeia that represents the sound of snoring.",
    "choices": [
      {
        "id": "A",
        "text": "Though they both represent the sound of snoring, the onomatopoeias \"korrrr\" (Batak) and \"hu lu\" (Mandarin Chinese) are written and pronounced very differently."
      },
      {
        "id": "B",
        "text": "Onomatopoeias, words that imitate the sounds they represent, are often written and pronounced very differently from language to language."
      },
      {
        "id": "C",
        "text": "The Batak word \"korrrr\" and the Mandarin Chinese word \"hu lu\" are onomatopoeias that represent the sound of snoring."
      },
      {
        "id": "D",
        "text": "The Batak word \"korrrr,\" which represents the sound of snoring, is an onomatopoeia."
      }
    ],
    "correctAnswer": "A",
    "type": "multiple-choice",
    "category": {
      "subject": "English",
      "domain": "Expression of Ideas",
      "skill": "Rhetorical Synthesis",
      "confidence": "high"
    }
  }
];
