export const countryPageClasses = {
  page: "mx-auto max-w-3xl px-6 py-10",
  nav: "mb-6 text-sm text-muted-foreground",
  homeLink: "hover:underline",
  navCurrent: "text-foreground",
  title: "text-4xl font-semibold tracking-tight md:text-5xl",
  intro: "mt-4 text-lg text-muted-foreground",
  section: "mt-10",
  sectionTitle: "text-2xl font-semibold tracking-tight",
  paragraph: "mt-3 text-muted-foreground",
  bulletList: "mt-3 list-disc space-y-1 pl-6 text-muted-foreground",
  faqList: "mt-4 space-y-5",
  faqQuestion: "text-base font-semibold",
  faqAnswer: "mt-1 text-muted-foreground",
  card: "mt-10 rounded-xl border border-border p-5",
  topicCard: "rounded-xl border border-border p-4",
  topicLink: "text-base font-semibold hover:underline",
  topicDescription: "mt-1 text-sm text-muted-foreground",
  actionLink: "rounded-lg border border-border px-3 py-2 text-sm font-semibold hover:bg-muted",
  tableCell: "px-4 py-3 text-muted-foreground",
} as const;
