#!/usr/bin/env python3
"""Codex (gpt-5.4) review pass for flagged explanations.

Reads grades.json, picks entries where correctness < 5 or 5-dim avg < 4.5,
and asks Codex to either (a) confirm the explanation is fine (judge false
positive) or (b) produce a rewritten explanation in the same schema.

Usage:
    python scripts/codex_review.py \
        --bank src/data/questions/math_past.json \
        --out /tmp/expl-stage1/math \
        --grades /tmp/expl-stage1/math-grades.json \
        --log /tmp/expl-stage1/math-codex.jsonl
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "verdict": {"type": "string", "enum": ["ok", "rewrite"]},
        "reason": {"type": "string"},
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "content": {"type": "string"},
                    "formula": {"type": "string"},
                },
                "required": ["title", "content"],
            },
        },
    },
    "required": ["verdict", "reason"],
}


REVIEW_PROMPT = """You are a senior SAT tutor doing a final QA pass on an explanation that another model (Haiku) generated and that a judge flagged.

Your job: decide whether the explanation is actually wrong, or whether the judge was mistaken.

If the explanation is correct and pedagogically sound (even if the judge complained), return:
{{"verdict": "ok", "reason": "<one short sentence>"}}

If the explanation has a real problem (wrong reasoning, skipped step, unclear logic, incorrect grammar rule, etc.), rewrite it. Return:
{{"verdict": "rewrite", "reason": "<what was wrong>", "steps": [<new steps>]}}

REWRITE REQUIREMENTS:
- 2-4 steps. Math prefers 2-3. Reading is 2.
- Solve forward. Never reveal the answer before deriving it.
- End the last step with its own sentence in exactly this form:
  "That matches choice {correct} \u2014 <strong>{correct}</strong> is correct."
- No hedging ("may", "might", "seems", "appears"). No doubt ("let's re-examine", "wait", "actually").
- Use HTML tags (<strong>, <br/>, <em>, <ul><li>). Inline math $...$, display math $$...$$.
- Every backslash in LaTeX must be doubled: "\\\\frac", "\\\\sqrt", "\\\\cdot".
- No straight quote marks (\") inside string values \u2014 use curly quotes \u201c \u201d or <em> tags.
- For fill-in-blank / grid-in (no letter choice), replace the tie-in with:
  "Therefore the answer is <strong>{correct}</strong>."

QUESTION:
Section: {section}
Skill: {skill}
Difficulty: {difficulty}

{text}

CHOICES:
{choices}

CORRECT ANSWER: {correct}

CURRENT EXPLANATION (generated by Haiku):
{explanation}

JUDGE'S COMPLAINT:
{complaint}

Return ONLY a single JSON object matching the required schema. No commentary."""


def is_flagged(g: dict) -> bool:
    if "error" in g:
        return True
    if g.get("correctness", 5) < 5:
        return True
    avg = (g.get("correctness", 5) + g.get("efficiency", 5)
           + g.get("confidence", 5) + g.get("non_redundancy", 5)
           + g.get("readability", 5)) / 5
    return avg < 4.5


def build_prompt(q: dict, expl: dict, grade: dict) -> str:
    choices_str = "\n".join(f"{c['id']}) {c['text']}" for c in q.get("choices", []))
    complaint = "; ".join(grade.get("issues", []) or ["(no specific issues listed)"])
    scores = (f"correctness={grade.get('correctness')}, efficiency={grade.get('efficiency')}, "
              f"confidence={grade.get('confidence')}, non_redundancy={grade.get('non_redundancy')}, "
              f"readability={grade.get('readability')}")
    complaint = f"{scores}; {complaint}"
    return REVIEW_PROMPT.format(
        correct=q.get("correctAnswer", "?"),
        section=q.get("section", "?"),
        skill=q.get("skill", "?"),
        difficulty=q.get("difficulty", "?"),
        text=q.get("text", ""),
        choices=choices_str or "(fill-in-blank, no choices)",
        explanation=json.dumps(expl.get("steps", []), indent=2),
        complaint=complaint,
    )


def call_codex(prompt: str, schema_path: Path, image_paths: list[Path]) -> dict | None:
    """Invoke `codex exec` with strict JSON-schema output. Returns parsed JSON or None."""
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as tf:
        out_path = tf.name
    cmd = [
        "codex", "exec",
        "--skip-git-repo-check",
        "--sandbox", "read-only",
        "--output-schema", str(schema_path),
        "-o", out_path,
    ]
    for p in image_paths:
        cmd += ["-i", str(p)]
    cmd += [prompt]
    try:
        subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    except subprocess.TimeoutExpired:
        return None
    try:
        raw = Path(out_path).read_text().strip()
    except Exception:
        return None
    finally:
        try: os.unlink(out_path)
        except Exception: pass
    if not raw:
        return None
    # Codex may wrap in fences; strip.
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
    if raw.startswith("json\n"):
        raw = raw[5:]
    start = raw.find("{"); end = raw.rfind("}")
    if start < 0 or end < 0:
        return None
    try:
        return json.loads(raw[start:end + 1])
    except json.JSONDecodeError:
        return None


def resolve_image_paths(q: dict) -> list[Path]:
    """Same path-remap as gen_explanation_trial, for visual questions."""
    roots = [
        Path(".claude/worktrees/sweet-yonath/public/images/SAT-Style Questions"),
        Path("public/images/SAT-Style Questions"),
    ]
    out = []
    for im in q.get("images") or []:
        local = im.get("local", "")
        name = os.path.basename(local)
        stem = re.sub(r"_\d+(\.[a-z]+)$", r"\1", name)
        for root in roots:
            found = False
            for cand in {name, stem}:
                p = root / cand
                if p.exists():
                    out.append(p.resolve())
                    found = True
                    break
            if found:
                break
    return out


def review_one(q: dict, grade: dict, out_dir: Path, schema_path: Path) -> dict:
    qid = q["id"]
    epath = out_dir / f"{qid}.json"
    if not epath.exists():
        return {"qid": qid, "action": "skip", "reason": "no explanation file"}
    try:
        expl = json.loads(epath.read_text())
    except json.JSONDecodeError:
        return {"qid": qid, "action": "skip", "reason": "explanation is not valid JSON"}

    prompt = build_prompt(q, expl, grade)
    imgs = resolve_image_paths(q)
    verdict = call_codex(prompt, schema_path, imgs)
    if verdict is None:
        return {"qid": qid, "action": "error", "reason": "codex empty/invalid response"}

    if verdict.get("verdict") == "ok":
        return {"qid": qid, "action": "kept", "reason": verdict.get("reason", "")}

    if verdict.get("verdict") == "rewrite" and verdict.get("steps"):
        new = dict(expl)
        new["steps"] = verdict["steps"]
        # Back up original for audit trail
        backup = epath.with_suffix(".haiku.json")
        if not backup.exists():
            backup.write_text(epath.read_text())
        epath.write_text(json.dumps(new, indent=2))
        return {"qid": qid, "action": "rewritten",
                "reason": verdict.get("reason", ""),
                "new_step_count": len(verdict["steps"])}

    return {"qid": qid, "action": "error", "reason": f"unexpected verdict: {verdict}"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bank", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--grades", required=True)
    ap.add_argument("--log", required=True, help="JSONL log of review actions")
    ap.add_argument("--workers", type=int, default=4,
                    help="Codex parallelism (keep low; codex is slow and expensive)")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    bank = {q["id"]: q for q in json.loads(Path(args.bank).read_text())}
    grades = json.loads(Path(args.grades).read_text())
    flagged = [g for g in grades if is_flagged(g) and g["questionId"] in bank]
    if args.limit:
        flagged = flagged[: args.limit]
    print(f"Flagged: {len(flagged)} of {len(grades)} graded.", flush=True)

    # Already-reviewed ids (resumable)
    done_ids: set[str] = set()
    log_path = Path(args.log)
    if log_path.exists():
        for line in log_path.read_text().splitlines():
            try:
                done_ids.add(json.loads(line)["qid"])
            except Exception:
                pass
    flagged = [g for g in flagged if g["questionId"] not in done_ids]
    print(f"To review: {len(flagged)} (skipping {len(done_ids)} already reviewed)", flush=True)

    # Schema file for codex
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tf:
        json.dump(SCHEMA, tf)
        schema_path = Path(tf.name)

    out_dir = Path(args.out)
    counts = {"kept": 0, "rewritten": 0, "skip": 0, "error": 0}
    log_fh = log_path.open("a")
    try:
        with ThreadPoolExecutor(max_workers=args.workers) as ex:
            futs = {ex.submit(review_one, bank[g["questionId"]], g, out_dir, schema_path): g["questionId"]
                    for g in flagged}
            for i, fut in enumerate(as_completed(futs), 1):
                res = fut.result()
                counts[res["action"]] = counts.get(res["action"], 0) + 1
                log_fh.write(json.dumps(res) + "\n"); log_fh.flush()
                print(f"[{i}/{len(flagged)}] {res['qid'][:24]} {res['action']:10} {res['reason'][:80]}",
                      flush=True)
    finally:
        log_fh.close()
        try: os.unlink(schema_path)
        except Exception: pass

    print(f"\nDONE: {counts}", flush=True)


if __name__ == "__main__":
    main()
